name: "Project Add Issue"
description: "Add an issue to a project"
author: "Austen Stone"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  project_number:
    description: "The number of the project. Get this from the URL."
    required: true
  owner:
    description: "The owner of the project. Either the organization or the user."
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "plus"
  color: "blue"
