name: "Project Add"
description: "Add an issue or pull request to a project (beta)"
author: "Austen Stone"
inputs:
  project-number:
    description: "The number of the project. Get this from the URL."
    required: true
  github-token:
    description: "The GITHUB_TOKEN secret"
    default: ${{ github.token }}
  organization:
    description: "The organization that owns the project."
  user:
    description: "The user that owns the project."
  fields:
    description: "The fields to modify."
  fields-value:
    description: "The fields values."

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "plus"
  color: "blue"
