name: "Project Add Issue"
description: "Add an issue to a project (beta)"
author: "Austen Stone"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  project-number:
    description: "The number of the project. Get this from the URL."
    required: true
  organization:
    description: "The organization that owns the project."
    required: false
  user:
    description: "The user that owns the project."
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "plus"
  color: "blue"
