name: "OpenAI Issue Labeler"
description: "Labels issues using OpenAI's Classification API powered by GPT-3 models!"
author: "Austen Stone"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  project_number:
    description: "The number of the project. Get this from the URL."
    required: true
  owner:
    description: "The owner of the project. Either the organization or the user."
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "arrow-up-circle"
  color: "green"
